<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>
  <script>tinymce.init({ selector:'textarea' });</script>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "http://localhost/Skeletonv3/public/fronten/grammar";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<header id="head" class="secondary">
        <div class="container">
            <h1>GRAMMAR</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing eliras scele!</p>
        </div>
</header>
<!-- <div class="container"> -->
<!-- <div class="content_resize"> -->
<div class="container">
	<!-- <div class="row">
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	  <div class="col-md-1">.col-md-1</div>
	</div> -->

	<div class="col-md-2">
	<div class="gadget">
	          <h2 class="star"><span>Category</h2>
	  <ul class="sb_menu">
	    <li><a href="#">Home</a></li>
	    <li><a href="#">TemplateInfo</a></li>
	    <li><a href="#">Style Demo</a></li>
	    <li><a href="#">Blog</a></li>
	    <li><a href="#">Archives</a></li>
	    <li><a href="#">Website Templates</a></li>
	  </ul>
	</div>
	<div class="gadget">
	  <h2 class="star"><span>Sponsors</span></h2>
	  <ul class="ex_menu">
	    <li><a href="#">DreamTemplate</a><br />
	      Over 6,000+ Premium Web Templates</li>
	    <li><a href="#">TemplateSOLD</a><br />
	      Premium WordPress &amp; Joomla Themes</li>
	    <li><a href="#">ImHosted.com</a><br />
	      Affordable Web Hosting Provider</li>
	    <li><a href="#">DreamStock</a><br />
	      Download Amazing Stock Photos</li>
	    <li><a href="#">Evrsoft</a><br />
	      Website Builder Software &amp; Tools</li>
	    <li><a href="#">MyVectorStore</a><br />
	      Royalty Free Stock Icons</li>
	  </ul>
	</div>
	</div>
	<div class="col-md-8">	
	<!-- <textarea>Next, start a free trial!</textarea> -->
        <div class="article">
          <h2><span>A Blog</span> Entry</h2>
          <p>Posted by <a href="#">Owner</a> &nbsp;&nbsp;|&nbsp;&nbsp; Filed under <a href="#">templates</a>, <a href="#">internet</a></p>
          <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. Donec mattis, purus nec placerat bibendum, dui pede condimentum odio, ac blandit ante orci ut diam. Cras fringilla magna. Phasellus suscipit, leo a pharetra condimentum, lorem tellus eleifend magna, eget fringilla velit magna id neque. Curabitur vel urna. In tristique orci porttitor ipsum. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec libero. Suspendisse bibendum. Cras id urna. Morbi tincidunt, orci ac convallis aliquam, lectus turpis varius lorem, eu posuere nunc justo tempus leo. </p>
          <p>Tagged: <a href="#">orci</a>, <a href="#">lectus</a>, <a href="#">varius</a>, <a href="#">turpis</a></p>
          <p><a href="#"><strong>Comments (3)</strong></a> &nbsp;&nbsp;|&nbsp;&nbsp; May 27, 2015 &nbsp;&nbsp;|&nbsp;&nbsp; <a href="#"><strong>Edit</strong></a></p>
        </div>
       	<div class="fb-comments" data-href="http://localhost/Skeletonv3/public/fronten/grammar" data-numposts="5"></div>
        
    </div>
	<div class="col-md-2">
	<div class="gadget">
	          <h2 class="star">Topic</h2>
	  <ul class="sb_menu">
	    <li><a href="#">Home</a></li>
	    <li><a href="#">TemplateInfo</a></li>
	    <li><a href="#">Style Demo</a></li>
	    <li><a href="#">Blog</a></li>
	    <li><a href="#">Archives</a></li>
	    <li><a href="#">Website Templates</a></li>
	  </ul>
	</div>
	<div class="gadget">
	  <h2 class="star"><span>Sponsors</span></h2>
	  <ul class="ex_menu">
	    <li><a href="#">DreamTemplate</a><br />
	      Over 6,000+ Premium Web Templates</li>
	    <li><a href="#">TemplateSOLD</a><br />
	      Premium WordPress &amp; Joomla Themes</li>
	    <li><a href="#">ImHosted.com</a><br />
	      Affordable Web Hosting Provider</li>
	    <li><a href="#">DreamStock</a><br />
	      Download Amazing Stock Photos</li>
	    <li><a href="#">Evrsoft</a><br />
	      Website Builder Software &amp; Tools</li>
	    <li><a href="#">MyVectorStore</a><br />
	      Royalty Free Stock Icons</li>
	  </ul>
	</div>
	</div>
</div>
<div class="clr"></div>
<!-- </div> -->
<!-- </div> -->