<?php
$this->headScript()->prependFile($this->basePath('bksource/myjs/blog.js'));
use Zend\Db\Resultset\Resultset;
$set = new ResultSet();
$set->initialize($this->categories);
$buff = array();
$i = 0;
//$x = $set->toArray();
?>
<form id="add-category" class="col-sm-6">
  <div class="form-group">
    <label for="exampleInputEmail1">Add a new category</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
  </div>
  <div class="form-group">
  <label class="control-label">Category Parent</label>
  <select class="form-control" name="parent" id="parent">

    <option value="0" selected>Root</option>
    <?php 
    foreach ($set as $row) :
      $buff[$i] = $row;
      $i++;
    ?>
      <option value=<?= $this->escapeHtml($row->id) ?>><?= $this->escapeHtml($row->title)?></option>
    <?php endforeach; ?>

  </select>
</div>
  <button type="submit" class="btn btn-primary pull-right">Add</button>
</form>
<!-- <hr class="col-sm-12"> -->
<table class="table">
<tr>
    <th>ID</th>
    <th>Title</th>    
    <th>Parent</th>
    <th>&nbsp;</th>
</tr>
<?php
 //$set->initialize($this->categories);
//$set2 = new ResultSet();
//$set2->initialize($this->categories);
 //for ($set as $row) :
  for ($i = 0; $i < count($buff);$i++):$row = $buff[$i]?>
      
<tr>
  <td class="id"><?= $this->escapeHtml($row->id) ?></td>
  <td class="title"><?= $this->escapeHtml($row->title) ?></td>
  <td class="parent"><?= $this->escapeHtml($row->parent) ?></td>
  <td>
    <a class="edit-item" data-toggle="modal" data-target="#myModal" href="<?= $this->url('ajax', ['action' => 'editCategory', 'id' => $row->id]) ?>" >
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Edit
    </a>
    <a class="delete-item text-danger" href="<?= $this->url('ajax', ['action' => 'deleteCategory', 'id' => $row->id]) ?>">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        Delete
    </a>
    
  </td>
</tr>
<?php endfor; ?>
</table>
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Launch demo modal
</button>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Modal title</h4>
      </div>
      <div class="modal-body">
         <div class="form-group">
          <label for="exampleInputEmail2"></label>
          <input type="text" class="form-control" id="title-update" name="title-update" placeholder="Title">
          <input id="id-update" type="hidden">
        </div>
        <div class="form-group">
        <label class="control-label">Category Parent</label>
        <select class="form-control" name="parent-update" id="parent-update">

          <option value="0" selected>Root</option>
          <?php 
          for ($i = 0; $i < count($buff);$i++):$row = $buff[$i]?>
          ?>
            <option value=<?= $this->escapeHtml($row->id) ?>><?= $this->escapeHtml($row->title)?></option>
          <?php endfor; ?>

        </select>
      </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->