<?php
$this->headScript()->prependFile($this->basePath('bksource/myjs/blog.js'));
$this->headScript()->prependFile($this->basePath('js/category.js'));
$this->headScript()->prependFile($this->basePath('js/article.js'));
use Zend\Db\Resultset\Resultset;
// $set = new ResultSet();
// $set->initialize($categories);
// $buff = array();
$i = 0;
$this->headLink()->appendStylesheet($this->basePath('css/summernote.css'));?>
<div class="row">
<div class="form-group">
  <button type="button" class="btn btn-primary" id="save-article">Save</button>
  </div>
</div>
<div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
</div>
<div class="row">
<div class="form-group">
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  Categories
</button>
<button type="button" class="btn btn-primary btn-lg" id="test">
  Test
</button>
</div>
<ol id="categories-selected" class="breadcrumb">
  <span class=" glyphicon glyphicon-hand-right" aria-hidden="true"></span>
</ol>
</div>
<div id="summernote">Hello Summernote</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">This article belongs to those categories</h4>
      </div>
      <div class="modal-body" id="list-categories">
         
        
      </div>
      </div>
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script src= <?= $this->basePath('js/summernote.js')?> type="text/javascript"></script> 
<script type="text/javascript">
	$(document).ready(function() {
	  $('#summernote').summernote();
	});
</script>
<script type="text/javascript">
  
</script>