<?php
$this->headScript()->prependFile($this->basePath('bksource/myjs/blog.js'));
$this->headScript()->prependFile($this->basePath('js/category.js'));
$this->headLink()->prependStylesheet($this->basePath('bksource/css/style.css'));
use Zend\Db\Resultset\Resultset;
// $set = new ResultSet();
// $set->initialize($categories);
// $buff = array();
$i = 0;
//$x = $set->toArray();
// foreach($categories as $x){
//   echo "<p>".$x->id."</p>";
// }

?>
<form id="add-category" class="col-sm-6">
  <br/>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">New Category</h3>
  </div>
  <div class="panel-body">
    <div class="form-group">
    <label for="exampleInputEmail1">Category Title</label>
    <input type="text" class="form-control" id="title" name="title" placeholder="Title">
  </div>
  <?php 
    function cat_sort($a,$b){
      if($a->id == 1){return -1;}
      if($b->id == 1){return 1;}
      
      if($a->parent == $b->parent){
        return 0;
      }
      return ($a->parent < $b->parent)? -1:1;
    }
    function parent($rows,$cats){
      foreach($cats as $p){
        if($rows->parent == $p->id){
          return $p;
        }
      }
    }
    foreach ($categories as $row){
      $buff[$i] = $row;
      $i++;
    }
    usort($buff,"cat_sort");
    ?>
     
  <div class="form-group">
  <label class="control-label">Category Parent</label>
  <select class="form-control" name="parent" id="parent">

    <!-- <option value="0" selected>Root</option> -->
    

  </select>
</div>
<div class="form-group">
  <button type="submit" class="btn btn-primary pull-right">Add</button>
</div>
  </div>

</div>
  
  
</form>
<!-- <hr class="col-sm-12"> -->
<div class="col-md-3 pull-right" id="list-categories">


</div>

<div class="col-md-8">
<table class="table">
<tr>
    <th>ID</th>
    <th>Title</th>    
    <th>Parent</th>
    <th>&nbsp;</th>
</tr>
<?php
 //$set->initialize($this->categories);
//$set2 = new ResultSet();
//$set2->initialize($this->categories);
 //for ($set as $row) :
  for ($i = 0; $i < count($buff);$i++):$row = $buff[$i]?>
      
<tr>
  <td><?= $i+1 ?></td>
  <td class="id collapse"><?= $this->escapeHtml($row->id) ?></td>
  <td class="title"><?= $this->escapeHtml($row->title) ?></td>
  <td class="parent"><?= $this->escapeHtml(parent($row,$buff)->title) ?></td>
  <td>
    <a class="edit-item" data-toggle="modal" data-target="#myModal" href="<?= $this->url('blog', ['action' => 'editCategory', 'id' => $row->id]) ?>" >
        <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
        Edit
    </a>
    <a class="delete-item text-danger" href="<?= $this->url('blog', ['action' => 'deleteCategory', 'id' => $row->id]) ?>">
        <span class="glyphicon glyphicon-remove-sign" aria-hidden="true"></span>
        Delete
    </a>
    
  </td>
</tr>
<?php endfor; ?>
</table>


<div class="clr" style="clear: both;"></div>

<script type="text/javascript">
  $.ajax({
      url: $("#base_path").val()+'/blog/getCategories',//$("#submit-url").val(),
      type: 'POST',
      dataType: 'json',
      //contentType: "application/json; charset=utf-8",
      async: true,
      //data: ($("#add-category").serialize()),
      success: function (data) {
          //obj = JSON.parse(data);
          tree = data.tree;
          arr = data.arr;
          print_cat(tree);
          console.log("tree: "+JSON.stringify(tree));
          //console.log("tree: "+JSON.stringify(tree["1"]));
          console.log("arr: "+JSON.stringify(arr));
          //location.reload(); 
          ul = print_tree("1",arr,tree);
          console.log("-->"+ul); 
          $("#list-categories").html(ul);
          $("#parent").html(print_select("1",arr,tree,0));
      },
      error: function (data,status,err) {                
          console.log("data:--->"+data.responseText);
          console.log("Status---->"+status);
          console.log("Error--->"+err);

      }
  });
</script>